# You can make local adjustments by creating a site.yml file and overriding the settings here.

# The subtitle to display on every page. May contain HTML.
# Example: HELSINKI UNIVERSITY<br />Department of Computer Science
site_subtitle:

# In many installations, tmp/cache/git_repos must be available to the apache user.
# Either give everyone read access to it (the default) or give the tmc server user
# and the apache user a common group and set chmod: g+rX and chgrp: the-common-group.
# These settings will be applied to tmp, tmp/cache and tmp/cache/git_repos as well.
git_repos_chmod: a+rX
git_repos_chgrp:

# A remote sandbox will need to contact the web server when it's done processing.
# Enter the baseurl of the webapp with which the sandboxes will find the web server.
baseurl_for_remote_sandboxes: http://localhost:3000/

# Settings for e-mails.
emails:
  reset_password:
    baseurl: http://localhost:3000/
    from: noreply@example.com

# List at least one sandbox instance here (in site.yml).
#
# Any URL will do. Example:
# http://user:password@sandbox.example.com:3001/path/to/the/sandbox/service
#
# The default points to the local instance that may be started with `rake sandbox:local:start`.
#
remote_sandboxes:
  - http://localhost:3001/

# Whether to show the model solution immediately after
# a student has completed the exercise.
#
# The NetBeans plugin will not advertise the model solution
# if this is set to false.
show_model_solutions_when_exercise_completed: true

